apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: servas
  name: servas
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: servas
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: servas
    spec:
      containers:
        - image: beromir/servas
          name: servas
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /app/.env
              name: servas-cm0
              subPath: .env
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: .env
                path: .env
            name: servas-cm0
          name: servas-cm0
